export const SERVICE_AREAS = [
  'ALBERTON',
  'BRACKENHURST',
  'BRACKENDOWNS',
  'MEYERSDAL',
  'GLENVISTA',
  'GLENANDA',
  'MULBARTON',
  'KIBLER PARK',
  'RIS PARK',
  'MAYFIELD PARK',
  'ABMERE',
  'BASONIA',
  'RANDHART',
  'MAYBERRY PARK',
  'ALBERTSDAL',
  'ALRODE',
  'LANGLAAGTE',
  'EIKENHOF',
  'RIETFLEI',
  'ALAN MANOR',
  'MEREDALE',
  'SOUTH GATE',
  'NEW MARKET',
  'GENERAL ALBERTS PARK',
  'ALBERANTE',
  'RACEVIEW,NEW REDROOTH',
  'FLORANTIA',
  'SOUTH CREST,TULISA PARK',
  'LEAPORDS REST',
  'SKY CITY',
];

// The Johannesburg metro locations confirmed for this business.
export const PRIMARY_AREAS = [
  'Johannesburg',
  'Sandton',
  'Randburg',
  'Roodepoort',
  'Midrand',
  'Centurion',
  'Pretoria East',
  'Pretoria West',
  'Germiston',
  'Boksburg',
  'Krugersdorp',
  'Benoni',
];
